import Head from 'next/head';
import Cards from '../components/Cards';
import Hero from '../components/Hero';

const Home = () => {
  return (
    <div>
      <Head>
        <title>ESBA DIVE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading='Esba Dive' message='Cursos de buceo con certificacion internacional'/>
      <Cards />
    </div>
  
  )
};

export default Home;
